/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "wifi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Xense_Station, Xense_Station, AUTO)


PB_BIND(Xense_AccessPoint, Xense_AccessPoint, AUTO)


PB_BIND(Xense_ScanResult, Xense_ScanResult, 2)



