/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "./xense.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Xense_gps, Xense_gps, AUTO)


PB_BIND(Xense_metadata, Xense_metadata, AUTO)


PB_BIND(Xense_state, Xense_state, AUTO)


PB_BIND(Xense_data, Xense_data, AUTO)



